const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const today=new Date().toISOString().slice(0,10), state={faqs:[],sources:[],coverData:"",coverPath:"",bodyImages:{},mode:"visual",selectedCell:null,selectedCells:[],selecting:false,resize:null,colorCommand:"foreColor",savedRange:null};
const allowed=new Set("P BR H2 H3 H4 STRONG B EM I U S BLOCKQUOTE UL OL LI A HR SECTION ASIDE DIV SPAN FIGURE FIGCAPTION IMG TABLE THEAD TBODY TFOOT TR TH TD COLGROUP COL".split(" "));
$("#publishedAt").value=today;
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function id(){return`img-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function slugify(v){return v.trim().toLowerCase().replace(/[^a-z0-9가-힣]+/g,"-").replace(/[가-힣]/g,"").replace(/-+/g,"-").replace(/^-|-$/g,"")}
function toast(m,e=false){const x=$("#toast");x.textContent=m;x.className=`toast is-visible${e?" is-error":""}`;clearTimeout(toast.t);toast.t=setTimeout(()=>x.className="toast",3200)}
function fileData(f){return new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)})}
function cleanHtml(source){const doc=new DOMParser().parseFromString(`<div id="root">${source}</div>`,"text/html"),root=doc.querySelector("#root");root.querySelectorAll("script,style,iframe,object,embed,form,input,button,textarea,select,option,link,meta,base,svg,math").forEach(n=>n.remove());[...root.querySelectorAll("*")].forEach(el=>{if(!allowed.has(el.tagName)){el.replaceWith(...el.childNodes);return}[...el.attributes].forEach(a=>{const name=a.name.toLowerCase(),value=a.value.trim();const ok=["href","target","rel","src","alt","title","width","height","colspan","rowspan","scope","class","id","style","data-editor-image"].includes(name);if(!ok||name.startsWith("on")||/javascript\s*:|data\s*:\s*text|expression\s*\(|url\s*\(/i.test(value))el.removeAttribute(a.name)});if(el.tagName==="A"){el.setAttribute("target","_blank");el.setAttribute("rel","noopener")}});return root.innerHTML.trim()}
function markdownToHtml(text=""){return text.trim().split(/\n{2,}/).filter(Boolean).map(chunk=>{const v=chunk.trim();if(/^#{1,3} /.test(v))return`<h2>${esc(v.replace(/^#{1,3}\s+/,""))}</h2>`;if(v.startsWith("> "))return`<blockquote>${esc(v.slice(2))}</blockquote>`;if(v.split("\n").every(x=>/^[-*] /.test(x)))return`<ul>${v.split("\n").map(x=>`<li>${esc(x.slice(2))}</li>`).join("")}</ul>`;return`<p>${esc(v).replace(/\*\*([^*]+)\*\*/g,"<strong>$1</strong>").replace(/\n/g,"<br>")}</p>`}).join("")}
function legacyDesign(blocks=[]){return blocks.map(b=>{if(b.type==="section")return`<section class="column-designed-section">${b.eyebrow?`<p class="column-section-label">${esc(b.eyebrow)}</p>`:""}<h2>${esc(b.heading)}</h2>${markdownToHtml(b.text)}</section>`;if(b.type==="checklist")return`<section class="column-designed-section"><h2>${esc(b.heading)}</h2><ul class="column-checklist">${(b.items||[]).map(x=>`<li><strong>${esc(x.title)}</strong><span>${esc(x.text)}</span></li>`).join("")}</ul></section>`;if(b.type==="cards")return`<section class="column-designed-section"><h2>${esc(b.heading)}</h2><div class="column-cases">${(b.items||[]).map((x,i)=>`<div><span>${String(i+1).padStart(2,"0")}</span><h3>${esc(x.title)}</h3><p>${esc(x.text)}</p></div>`).join("")}</div></section>`;if(b.type==="keypoint")return`<aside class="editor-keypoint">${esc(b.text)}</aside>`;return""}).join("")}
function sync(to){if(to==="html")$("#htmlEditor").value=cleanHtml($("#visualEditor").innerHTML);else $("#visualEditor").innerHTML=cleanHtml($("#htmlEditor").value);state.mode=to;$("#visualEditor").hidden=to!=="visual";$("#htmlEditor").hidden=to!=="html";$$('.mode').forEach(b=>b.classList.toggle("is-active",b.dataset.mode===to));scheduleSave()}
$$('.mode').forEach(b=>b.onclick=()=>sync(b.dataset.mode));
document.addEventListener("selectionchange",()=>{const selection=getSelection();if(!selection?.rangeCount)return;const range=selection.getRangeAt(0),node=range.commonAncestorContainer,nodeElement=node.nodeType===1?node:node.parentElement;if($("#visualEditor").contains(nodeElement))state.savedRange=range.cloneRange()});
function focusEditor(){if(state.mode==="html")sync("visual");$("#visualEditor").focus();if(state.savedRange){const selection=getSelection();selection.removeAllRanges();selection.addRange(state.savedRange)}}
function command(name,value=null){focusEditor();document.execCommand(name,false,value);scheduleSave()}
function applyFontSize(px){focusEditor();const range=state.savedRange;if(!range||range.collapsed)return toast("크기를 바꿀 글자를 먼저 드래그해 주세요.",true);const span=document.createElement("span");span.style.fontSize=`${px}px`;span.append(range.extractContents());range.insertNode(span);range.selectNodeContents(span);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);state.savedRange=range.cloneRange();scheduleSave()}
$$('[data-command]').forEach(b=>b.onclick=()=>command(b.dataset.command));$("#blockStyle").onchange=e=>command("formatBlock",e.target.value);$("#fontSize").onchange=e=>{if(e.target.value)applyFontSize(e.target.value)};$("#linkButton").onclick=()=>{const u=prompt("연결할 주소를 https://로 입력해 주세요","https://");if(u&&/^https:\/\//.test(u))command("createLink",u)};
const colors=["#27302d","#247860","#3c605a","#8b5e4a","#b33b3b","#ffffff","#f2eee9","#e5f1eb","#fff1b8","#dce9f5","#eedff0","#333333","#777777","#b7b7b7","#d9c3a5","#cf8877","#72a58f","#4e7898"];
function applyColor(cmd,color){if(state.selectedCells.length){state.selectedCells.forEach(c=>c.style[cmd==="cellBack"?"backgroundColor":"color"]=color);scheduleSave()}else command(cmd,color)}
function hsvHex(h,s,v){const f=n=>{const k=(n+h/60)%6;return v-v*s*Math.max(0,Math.min(k,4-k,1))};return`#${[f(5),f(3),f(1)].map(x=>Math.round(x*255).toString(16).padStart(2,"0")).join("")}`}
function openPalette(button,cmd){state.colorCommand=cmd;const p=$("#palette"),r=button.getBoundingClientRect();p.innerHTML=`<div class="swatches">${colors.map(c=>`<button data-color="${c}" style="background:${c}" title="${c}"></button>`).join("")}</div><div class="tone" tabindex="0"><i></i></div><input class="hue" type="range" min="0" max="360" value="155" aria-label="색상 계열"><div class="color-result"><span></span><input class="hex" value="#247860" maxlength="7" aria-label="HEX 색상값"><button data-apply>확인</button></div>`;p.hidden=false;p.style.left=`${Math.max(8,Math.min(r.left,innerWidth-270))}px`;p.style.top=`${Math.min(r.bottom+6,innerHeight-330)}px`;let hue=155,current="#247860",sat=.7,val=.75;const tone=p.querySelector(".tone"),dot=tone.querySelector("i"),result=p.querySelector(".color-result span"),hex=p.querySelector(".hex");function show(color){current=color.toUpperCase();result.style.background=current;hex.value=current}function pick(e){const q=tone.getBoundingClientRect(),x=Math.max(0,Math.min(q.width,e.clientX-q.left)),y=Math.max(0,Math.min(q.height,e.clientY-q.top));sat=x/q.width;val=1-y/q.height;dot.style.left=`${x}px`;dot.style.top=`${y}px`;show(hsvHex(hue,sat,val))}tone.style.setProperty("--tone",`hsl(${hue} 100% 50%)`);tone.onpointerdown=e=>{tone.setPointerCapture(e.pointerId);pick(e);tone.onpointermove=pick};tone.onpointerup=()=>tone.onpointermove=null;p.querySelector(".hue").oninput=e=>{hue=+e.target.value;tone.style.setProperty("--tone",`hsl(${hue} 100% 50%)`);show(hsvHex(hue,sat,val))};hex.oninput=e=>{let value=e.target.value.trim();if(value&&!value.startsWith("#"))value=`#${value}`;if(/^#[0-9a-f]{6}$/i.test(value)){current=value.toUpperCase();result.style.background=current;hex.classList.remove("is-invalid")}else hex.classList.add("is-invalid")};hex.onkeydown=e=>{if(e.key==="Enter"&&/^#[0-9a-f]{6}$/i.test(hex.value)){applyColor(cmd,current);p.hidden=true}};p.querySelectorAll("[data-color]").forEach(x=>x.onclick=()=>{applyColor(cmd,x.dataset.color);p.hidden=true});p.querySelector("[data-apply]").onclick=()=>{if(!/^#[0-9a-f]{6}$/i.test(hex.value))return hex.focus();applyColor(cmd,current);p.hidden=true};show(current)}
$("#textColorButton").onclick=e=>openPalette(e.currentTarget,"foreColor");$("#backColorButton").onclick=e=>openPalette(e.currentTarget,"hiliteColor");document.addEventListener("mousedown",e=>{if(!e.target.closest("#palette,#textColorButton,#backColorButton"))$("#palette").hidden=true});
function insertHtml(html){focusEditor();document.execCommand("insertHTML",false,html);scheduleSave()}
$$('[data-insert]').forEach(b=>b.onclick=()=>{const t=b.dataset.insert;if(t==="image")return $("#bodyImageFile").click();if(t==="h2")insertHtml("<h2>소제목을 입력해 주세요</h2><p><br></p>");if(t==="quote")insertHtml("<blockquote>인용하거나 강조할 문장을 입력해 주세요.</blockquote><p><br></p>");if(t==="keypoint")insertHtml('<aside class="editor-keypoint">가장 기억시키고 싶은 문장을 입력해 주세요.</aside><p><br></p>');if(t==="ul")insertHtml("<ul><li>첫 번째 항목</li><li>두 번째 항목</li></ul><p><br></p>");if(t==="hr")insertHtml("<hr><p><br></p>");if(t==="table")insertTable()});
function insertTable(){insertHtml('<table style="width:100%;table-layout:fixed"><colgroup><col style="width:33.33%"><col style="width:33.33%"><col style="width:33.34%"></colgroup><thead><tr><th>항목</th><th>내용</th><th>비고</th></tr></thead><tbody><tr><td>내용</td><td>내용</td><td>내용</td></tr><tr><td>내용</td><td>내용</td><td>내용</td></tr></tbody></table><p><br></p>')}
$("#bodyImageFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>5*1024*1024)return toast("사진은 5MB 이하로 골라 주세요.",true);const data=await fileData(f),key=id();state.bodyImages[key]=data;insertHtml(`<figure><img src="${data}" data-editor-image="${key}" alt="사진 설명을 입력해 주세요"><figcaption>사진 설명</figcaption></figure><p><br></p>`);e.target.value=""};
function tableGrid(table){const grid=[],placements=new Map();[...table.rows].forEach((row,r)=>{grid[r]??=[];let col=0;[...row.cells].forEach(cell=>{while(grid[r][col])col++;const rs=cell.rowSpan||1,cs=cell.colSpan||1;placements.set(cell,{r,c:col,rs,cs});for(let y=r;y<r+rs;y++){grid[y]??=[];for(let x=col;x<col+cs;x++)grid[y][x]=cell}col+=cs})});return{grid,placements}}
function paintSelection(cells){$$(".is-selected",$("#visualEditor")).forEach(x=>x.classList.remove("is-selected"));state.selectedCells=[...new Set(cells)].filter(Boolean);state.selectedCells.forEach(x=>x.classList.add("is-selected"));state.selectedCell=state.selectedCells[0]||null;$("#tablebar").hidden=!state.selectedCell;$("#cellCount").textContent=`${state.selectedCells.length}칸`}
function selectRange(a,b){if(!a||!b||a.closest("table")!==b.closest("table"))return;const {grid,placements}=tableGrid(a.closest("table")),x=placements.get(a),y=placements.get(b),r1=Math.min(x.r,y.r),r2=Math.max(x.r+x.rs-1,y.r+y.rs-1),c1=Math.min(x.c,y.c),c2=Math.max(x.c+x.cs-1,y.c+y.cs-1),cells=[];for(let r=r1;r<=r2;r++)for(let c=c1;c<=c2;c++)cells.push(grid[r]?.[c]);paintSelection(cells)}
function ensureCols(table){let group=table.querySelector("colgroup");const cols=tableGrid(table).grid[0]?.length||1;if(!group){group=document.createElement("colgroup");table.prepend(group)}while(group.children.length<cols)group.append(document.createElement("col"));[...group.children].forEach(col=>{if(!col.style.width)col.style.width=`${100/cols}%`});return group}
$("#visualEditor").addEventListener("pointerdown",e=>{const c=e.target.closest("td,th");if(!c){paintSelection([]);return}const rect=c.getBoundingClientRect(),edgeX=rect.right-e.clientX,edgeY=rect.bottom-e.clientY;if(edgeX<7){const table=c.closest("table"),group=ensureCols(table),pos=tableGrid(table).placements.get(c),col=group.children[pos.c];state.resize={kind:"col",start:e.clientX,size:col.getBoundingClientRect().width,node:col};e.preventDefault();return}if(edgeY<7){state.resize={kind:"row",start:e.clientY,size:c.parentElement.getBoundingClientRect().height,node:c.parentElement};e.preventDefault();return}state.selecting=true;state.selectedCell=c;paintSelection([c])});
$("#visualEditor").addEventListener("pointermove",e=>{if(state.resize){const delta=(state.resize.kind==="col"?e.clientX:e.clientY)-state.resize.start;state.resize.node.style[state.resize.kind==="col"?"width":"height"]=`${Math.max(36,state.resize.size+delta)}px`;return}const c=e.target.closest("td,th");if(c){const r=c.getBoundingClientRect();c.style.cursor=r.right-e.clientX<7?"col-resize":r.bottom-e.clientY<7?"row-resize":"cell";if(state.selecting&&e.buttons)selectRange(state.selectedCell,c)}});document.addEventListener("pointerup",()=>{if(state.resize)scheduleSave();state.resize=null;state.selecting=false});
function mergeCells(){const cells=state.selectedCells;if(cells.length<2)return toast("두 칸 이상 드래그해서 선택해 주세요.",true);const table=cells[0].closest("table");if(cells.some(c=>c.closest("table")!==table||c.rowSpan>1||c.colSpan>1))return toast("이미 병합된 셀은 먼저 분리해 주세요.",true);const {grid,placements}=tableGrid(table),ps=cells.map(c=>placements.get(c)),r1=Math.min(...ps.map(p=>p.r)),r2=Math.max(...ps.map(p=>p.r)),c1=Math.min(...ps.map(p=>p.c)),c2=Math.max(...ps.map(p=>p.c));for(let r=r1;r<=r2;r++)for(let c=c1;c<=c2;c++)if(!cells.includes(grid[r]?.[c]))return toast("사각형 영역으로 선택해 주세요.",true);const anchor=grid[r1][c1],texts=cells.map(c=>c.innerHTML).filter(Boolean);anchor.rowSpan=r2-r1+1;anchor.colSpan=c2-c1+1;anchor.innerHTML=texts.join("<br>");cells.filter(c=>c!==anchor).forEach(c=>c.remove());paintSelection([anchor])}
function splitCell(){const c=state.selectedCell;if(!c||c.rowSpan===1&&c.colSpan===1)return toast("병합된 셀을 선택해 주세요.",true);const table=c.closest("table"),{placements}=tableGrid(table),p=placements.get(c),tag=c.tagName.toLowerCase(),rs=c.rowSpan,cs=c.colSpan;c.rowSpan=1;c.colSpan=1;for(let r=p.r;r<p.r+rs;r++)for(let col=p.c;col<p.c+cs;col++){if(r===p.r&&col===p.c)continue;const row=table.rows[r],n=document.createElement(tag);n.innerHTML="내용";const fresh=tableGrid(table),before=[...row.cells].find(x=>fresh.placements.get(x)?.c>col);row.insertBefore(n,before||null)}paintSelection([c])}
$("#tablebar").onclick=e=>{const a=e.target.dataset.table,c=state.selectedCell;if(!a||!c)return;if(a==="cell-back")return openPalette(e.target,"cellBack");if(a==="cell-text")return openPalette(e.target,"cellText");if(a==="merge"){mergeCells();return scheduleSave()}if(a==="split"){splitCell();return scheduleSave()}const row=c.parentElement,table=c.closest("table"),place=tableGrid(table).placements.get(c),idx=place.c;if(a==="row-after"){const n=row.cloneNode(true);[...n.cells].forEach(x=>{x.innerHTML="내용";x.removeAttribute("rowspan");x.removeAttribute("colspan")});row.after(n)}if(a==="col-after"){const group=ensureCols(table),col=document.createElement("col");group.insertBefore(col,group.children[idx+1]||null);table.querySelectorAll("tr").forEach(r=>{const x=document.createElement((r.parentElement.tagName==="THEAD"?"th":"td"));x.innerHTML="내용";r.insertBefore(x,r.cells[idx+1]||null)})}if(a==="row-delete")row.remove();if(a==="col-delete"){table.querySelectorAll("tr").forEach(r=>r.cells[idx]?.remove());ensureCols(table).children[idx]?.remove()}if(a==="header")state.selectedCells.forEach(old=>{const tag=old.tagName==="TH"?"td":"th",n=document.createElement(tag);n.innerHTML=old.innerHTML;[...old.attributes].forEach(x=>n.setAttribute(x.name,x.value));old.replaceWith(n);if(old===state.selectedCell)state.selectedCell=n});if(a==="table-delete"){table.remove();state.selectedCell=null;state.selectedCells=[]}paintSelection(state.selectedCell?[state.selectedCell]:[]);scheduleSave()};
function renderLists(){for(const name of ["faqs","sources"]){$("#"+name).innerHTML=state[name].map((v,i)=>name==="faqs"?`<div class="list-row" data-i="${i}"><button>×</button><input data-k="question" value="${esc(v.question)}" placeholder="질문"><textarea data-k="answer" placeholder="답변">${esc(v.answer)}</textarea></div>`:`<div class="list-row" data-i="${i}"><button>×</button><input data-k="title" value="${esc(v.title)}" placeholder="자료 이름"><input data-k="url" value="${esc(v.url)}" placeholder="https://"></div>`).join("");$("#"+name).oninput=e=>{const row=e.target.closest(".list-row");if(row&&e.target.dataset.k)state[name][+row.dataset.i][e.target.dataset.k]=e.target.value,scheduleSave()};$("#"+name).onclick=e=>{if(e.target.tagName==="BUTTON"){state[name].splice(+e.target.closest(".list-row").dataset.i,1);renderLists();scheduleSave()}}}}
$("#addFaq").onclick=()=>{state.faqs.push({question:"",answer:""});renderLists()};$("#addSource").onclick=()=>{state.sources.push({title:"",url:""});renderLists()};
function bodyHtml(){if(state.mode==="html")return cleanHtml($("#htmlEditor").value);const clone=$("#visualEditor").cloneNode(true);$$('.is-selected',clone).forEach(c=>c.classList.remove("is-selected"));$$("td,th",clone).forEach(c=>c.style.removeProperty("cursor"));return cleanHtml(clone.innerHTML)}
function draft(images=true){return{content:{title:$("#title").value.trim(),slug:$("#slug").value.trim(),status:"draft",editorName:$("#editorName").value,category:$("#category").value,summary:$("#summary").value.trim(),lead:$("#summary").value.trim(),description:$("#summary").value.trim(),tags:$("#tags").value.split(",").map(x=>x.trim()).filter(Boolean),coverImage:state.coverPath,coverAlt:$("#coverAlt").value.trim(),publishedAt:$("#publishedAt").value,modifiedAt:today,bodyHtml:bodyHtml(),faqs:state.faqs,sources:state.sources},...(images?{coverData:state.coverData,bodyImages:state.bodyImages}:{})}}
function saveLocal(){localStorage.setItem("dear-column-editor-v2",JSON.stringify(draft(false)));$("#saveState").textContent=`이 브라우저에 자동 저장됨 · ${new Date().toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})}`}
let saveTimer;function scheduleSave(){clearTimeout(saveTimer);$("#saveState").textContent="저장 중…";saveTimer=setTimeout(saveLocal,450)}
$("#visualEditor").oninput=scheduleSave;$("#htmlEditor").oninput=scheduleSave;$$('textarea,input,select').forEach(x=>x.addEventListener("input",scheduleSave));$("#coverFile").onchange=async e=>{const f=e.target.files[0];if(f)state.coverData=await fileData(f),scheduleSave()};$("#title").onblur=()=>{if(!$("#slug").value)$("#slug").value=slugify($("#title").value)||`column-${today.replaceAll("-","")}`};
function settings(open){$("#settingsPanel").classList.toggle("is-open",open);$("#settingsPanel").setAttribute("aria-hidden",String(!open));$("#scrim").hidden=!open}$("#settingsButton").onclick=()=>settings(true);$("#closeSettings").onclick=()=>settings(false);$("#scrim").onclick=()=>settings(false);
function previewHtml(){const c=draft(false).content,heads=[...new DOMParser().parseFromString(c.bodyHtml,"text/html").querySelectorAll("h2")];const cover=state.coverData||(state.coverPath?`/draft-media/${state.coverPath}`:"");return`<!doctype html><html lang="ko"><head><meta charset="utf-8"><base href="/"><link rel="stylesheet" href="/css/style.css"><style>body{zoom:.82}.nav{position:relative}.column-article{padding-top:40px}.column-article__content table{width:100%;border-collapse:collapse;margin:2rem 0}.column-article__content th,.column-article__content td{padding:12px;border:1px solid #d4d8d5}.editor-keypoint{padding:2rem;background:#284a41;color:white;font-size:1.35rem;font-weight:700}</style></head><body class="column-article-body"><nav class="nav"><a class="nav__logo">DEAR</a></nav><main class="column-article"><article><header class="column-article__header"><p class="column-meta">${esc($("#category").selectedOptions[0]?.textContent||"마음")}</p><h1>${esc(c.title||"칼럼 제목")}</h1><p class="column-article__lead">${esc(c.summary||"제목 아래 소개 문장")}</p><div class="column-byline"><span>${esc(c.editorName)}</span><time>${c.publishedAt.replaceAll("-",".")}</time></div></header>${cover?`<figure class="column-article__hero"><img src="${cover}" alt=""></figure>`:""}<div class="column-article__layout"><aside class="column-toc"><p>CONTENTS</p><ol>${heads.map((h,i)=>`<li><a href="#pv-${i}">${esc(h.textContent)}</a></li>`).join("")}</ol></aside><div class="column-article__content">${c.bodyHtml}<section class="column-consult"><p class="column-section-label">CONSULTATION</p><h2>현재의 상태를<br>함께 살펴보고 싶다면</h2><p>불편함과 생활의 변화를 편하게 이야기해 주세요.</p></section>${state.faqs.length?`<section class="column-faq"><h2>자주 묻는 질문</h2>${state.faqs.map(f=>`<details><summary>${esc(f.question)}</summary><p>${esc(f.answer)}</p></details>`).join("")}</section>`:""}<section class="column-nap"><p class="column-section-label">DEAR KOREAN MEDICINE CLINIC</p><h2>디어한의원</h2><address>서울 서초구 사임당로 143 3층 309호, 310호<br>02-3486-1777</address></section></div></div></article></main></body></html>`}
function showPreview(){if(state.mode==="html")sync("visual");$("#preview").srcdoc=previewHtml();$("#previewModal").hidden=false}$("#previewButton").onclick=showPreview;$("#panelPreview").onclick=showPreview;$("#closePreview").onclick=()=>$("#previewModal").hidden=true;$$('[data-width]').forEach(b=>b.onclick=()=>{$$('[data-width]').forEach(x=>x.classList.remove("is-active"));b.classList.add("is-active");$("#preview").classList.toggle("is-mobile",b.dataset.width==="mobile")});
async function action(kind){if(kind==="publish"&&!confirm("검토를 마친 이 글을 홈페이지에 공개할까요?"))return;$$('button').forEach(b=>b.disabled=true);try{const res=await fetch(`/api/${kind}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft())}),data=await res.json();if(!res.ok)throw Error(data.message);state.coverPath=data.content?.coverImage||state.coverPath;state.coverData="";if(data.content?.bodyHtml){$("#visualEditor").innerHTML=cleanHtml(data.content.bodyHtml);$("#htmlEditor").value=data.content.bodyHtml;state.bodyImages={}}toast(data.message);if(data.localUrl){$("#preview").src=data.localUrl;$("#previewModal").hidden=false}saveLocal()}catch(e){toast(e.message,true)}finally{$$('button').forEach(b=>b.disabled=false)}}
$("#saveButton").onclick=()=>action("save");$("#publishButton").onclick=()=>action("publish");
try{const saved=JSON.parse(localStorage.getItem("dear-column-editor-v2")||localStorage.getItem("dear-column-editor"));if(saved?.content){const c=saved.content;for(const k of ["title","slug","summary","coverAlt","publishedAt"])if(c[k]&&$("#"+k))$("#"+k).value=c[k];$("#category").value=c.category||"Calm";$("#editorName").value=c.editorName||"김민지";$("#tags").value=(c.tags||[]).join(", ");$("#visualEditor").innerHTML=cleanHtml(c.bodyHtml||markdownToHtml(c.body||"")+legacyDesign(c.designBlocks));$$("img[data-editor-image]",$("#visualEditor")).forEach(img=>{if(img.src.startsWith("data:image/"))state.bodyImages[img.dataset.editorImage]=img.src});state.faqs=c.faqs||[];state.sources=c.sources||[];state.coverPath=c.coverImage||""}}catch{}renderLists();saveLocal();
